site: Sidey
url: "https://SEORY0.github.io"
title: "SEORY0"
description: "Security Researcher & CTF Player. Windows Kernel Exploitation, Reverse Engineering, and AI for Security."
twitter:
  username: SEORY0
  card: summary_large_image
  creator: SEORY0
author:
  twitter: SEORY0
  name: "SEORY0"
  avatar: "/assets/images/profile.jpg"
  email: seory0@outlook.kr
  url: "https://SEORY0.github.io"

# Open Graph defaults
og_image: "/assets/images/logo.png"
permalink: pretty

baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # line_numbers: true  <-- 이 옵션은 끄거나 주석 처리하세요! (CSS로 구현했습니다)
    # block:
    #   line_numbers: true
    span:
      line_numbers: false

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  books:
    output: true
    permalink: /books/:slug/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"